### ISSUE TITLE
https://github.com/m-a-hall/hop-cpython/issues/4

### ISSUE THREAD

**Issue by vutiendung** [m-a-hall/hop-cpython#11]
I have run the sample pipeline and got this error message.
Please assist us.

```
2023/10/30 18:55:10 - CPython Script Executor 2.0 - ERROR: Unexpected error
2023/10/30 18:55:10 - CPython Script Executor 4.0 - ERROR: Unexpected error
2023/10/30 18:55:10 - CPython Script Executor.0 - ERROR: Unexpected error
2023/10/30 18:55:10 - CPython Script Executor 4.0 - ERROR: org.apache.hop.core.exception.HopException: 
2023/10/30 18:55:10 - CPython Script Executor 4.0 - java.net.SocketException: Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor 4.0 - Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at org.phalanxdev.python.ServerUtils.sendRowsToPandasDataFrame(ServerUtils.java:580)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at org.phalanxdev.python.PythonSession.rowsToPythonDataFrame(PythonSession.java:779)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.rowsToPyDataFrame(CPythonScriptExecutor.java:474)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.processBatch(CPythonScriptExecutor.java:284)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.processRow(CPythonScriptExecutor.java:247)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at java.base/java.lang.Thread.run(Thread.java:834)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - Caused by: java.net.SocketException: Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:138)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at org.phalanxdev.python.ServerUtils.writeDelimitedToOutputStream(ServerUtils.java:965)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	at org.phalanxdev.python.ServerUtils.sendRowsToPandasDataFrame(ServerUtils.java:546)
2023/10/30 18:55:10 - CPython Script Executor 4.0 - 	... 6 more
2023/10/30 18:55:10 - CPython Script Executor 3.0 - ERROR: Unexpected error
2023/10/30 18:55:10 - CPython Script Executor 2.0 - ERROR: org.apache.hop.core.exception.HopException: 
2023/10/30 18:55:10 - CPython Script Executor 2.0 - java.net.SocketException: Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor 2.0 - Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at org.phalanxdev.python.ServerUtils.sendRowsToPandasDataFrame(ServerUtils.java:580)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at org.phalanxdev.python.PythonSession.rowsToPythonDataFrame(PythonSession.java:779)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.rowsToPyDataFrame(CPythonScriptExecutor.java:474)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.processBatch(CPythonScriptExecutor.java:284)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.processRow(CPythonScriptExecutor.java:247)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at java.base/java.lang.Thread.run(Thread.java:834)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - Caused by: java.net.SocketException: Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:138)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at org.phalanxdev.python.ServerUtils.writeDelimitedToOutputStream(ServerUtils.java:965)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	at org.phalanxdev.python.ServerUtils.sendRowsToPandasDataFrame(ServerUtils.java:546)
2023/10/30 18:55:10 - CPython Script Executor 2.0 - 	... 6 more
2023/10/30 18:55:10 - CPython Script Executor 3.0 - ERROR: org.apache.hop.core.exception.HopException: 
2023/10/30 18:55:10 - CPython Script Executor 3.0 - java.net.SocketException: Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor 3.0 - Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at org.phalanxdev.python.ServerUtils.sendRowsToPandasDataFrame(ServerUtils.java:580)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at org.phalanxdev.python.PythonSession.rowsToPythonDataFrame(PythonSession.java:779)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.rowsToPyDataFrame(CPythonScriptExecutor.java:474)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.processBatch(CPythonScriptExecutor.java:284)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.processRow(CPythonScriptExecutor.java:247)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at java.base/java.lang.Thread.run(Thread.java:834)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - Caused by: java.net.SocketException: Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:138)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at org.phalanxdev.python.ServerUtils.writeDelimitedToOutputStream(ServerUtils.java:965)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	at org.phalanxdev.python.ServerUtils.sendRowsToPandasDataFrame(ServerUtils.java:546)
2023/10/30 18:55:10 - CPython Script Executor 3.0 - 	... 6 more
2023/10/30 18:55:10 - CPython Script Executor 4.0 - Finished processing (I=0, O=0, R=150, W=0, U=0, E=1)
2023/10/30 18:55:10 - CPython Script Executor.0 - ERROR: org.apache.hop.core.exception.HopException: 
2023/10/30 18:55:10 - CPython Script Executor.0 - java.net.SocketException: Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor.0 - Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor.0 - 
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at org.phalanxdev.python.ServerUtils.sendRowsToPandasDataFrame(ServerUtils.java:580)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at org.phalanxdev.python.PythonSession.rowsToPythonDataFrame(PythonSession.java:779)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.rowsToPyDataFrame(CPythonScriptExecutor.java:474)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.processBatch(CPythonScriptExecutor.java:284)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at org.phalanxdev.hop.pipeline.transforms.cpython.CPythonScriptExecutor.processRow(CPythonScriptExecutor.java:247)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at java.base/java.lang.Thread.run(Thread.java:834)
2023/10/30 18:55:10 - CPython Script Executor.0 - Caused by: java.net.SocketException: Software caused connection abort: socket write error
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:138)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at org.phalanxdev.python.ServerUtils.writeDelimitedToOutputStream(ServerUtils.java:965)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	at org.phalanxdev.python.ServerUtils.sendRowsToPandasDataFrame(ServerUtils.java:546)
2023/10/30 18:55:10 - CPython Script Executor.0 - 	... 6 more
2023/10/30 18:55:10 - Py example - Pipeline detected one or more transforms with errors.
```

**Comment by NicoDupont** [comment]
I have the exact same error after installing all the necessary python libraries (pandas, numpy etc...)
Anyone can help us ?
thx !

**Comment by pauloricardoferreira** [comment]
Hello.

I compiled it with Apache Hop 2.9.0 and Java 11.
Python Version: 3.11

I am also getting the above error.
